### ISSUE TITLE
Code LICENSE?

### ISSUE THREAD

**Issue by brylie** [frozeman/book-building-single-page-web-apps-with-meteor#1]
Fabian,
I am just now starting to work through you book, and would like to upload my progress to a Github repository. Under what license is the book's sourcecode released?

Thanks!
Brylie

**Comment by frozeman** [comment]
MIT or the DWTFYW :)

**Comment by brylie** [comment]
Thanks for the quick response! I will place the MIT license in my repository.

**Comment by frozeman** [comment]
sure

**Comment by frozeman** [comment]
BTW thanks for reading :)
It would be hard for me to add the license now to all chapters, as i created a tag for each chapter.. so i better leave it as is..

**Comment by brylie** [comment]
That makes sense. If you don't mind my recommendation, it still may be worthwhile to add the LICENSE file to the repository as a new commit. This way, people who find the code will know the license permissions.
